# Generated by Django 3.1.7 on 2021-11-11 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventoryselled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventorySelled',
        ),
    ]
