# Generated by Django 3.1.7 on 2021-11-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_can_backorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='inventory',
        ),
    ]
