# Generated by Django 3.1.7 on 2021-11-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210322_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='inventory_updated',
            field=models.BooleanField(default=False),
        ),
    ]
